version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - postgres_data_go_guide:/var/lib/postgresql/data

volumes:
  postgres_data_go_guide:
